name: Hello, Heather
description: An Ember.js and JavaScript blog by Heather Brysiewicz
url: http://hbrysiewicz.com/
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title.html
baseurl: .
