name: Alexandra Brysiewicz
description: An Ember.js, Elixir, and JavaScript blog by Alexandra Brysiewicz
url: http://hbrysiewicz.com/
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title.html
baseurl: .
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
