name: Hello, Bunny
description: An Ember.js and JavaScript blog by Heather Brysiewicz
url: http://hbrysiewicz.com/
markdown: redcarpet
highlighter: rouge
permalink: /:year-:month-:day-:title.html
baseurl: .