name: "A Touch of Technology"
description: Technology writings from Alex Brysiewicz
url: http://hbrysiewicz.com/
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title.html
baseurl: .
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
kramdown:
  parse_block_html: true
